#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
# These settings will be merged into the default settings
title: PHYSICS LAB # The title of the book. Will be placed in the left navbar.
author: Jamie Vo (TA)  # The author of the book
copyright: "2021"  # Copyright year to be placed in the footer
logo: images/logo.jpg  # A path to the book logo



# Settings to repo location of the book
repository:
  url: https://github.com/thuanGIT/phys-web.git


# Settings for book building
only_build_toc_files: true

# Settings for HTML
html:
  home_page_in_navbar: true
    

parse:
  # (deprecated in >= v0.10.0)
  # This allows ::: syntax, which is friendly for markdown syntax rendering
  # myst_extended_syntax: true 

execute:
  jupyter_execute_notebooks: 'force'  